"""empty message

Revision ID: c3615b26dece
Revises: d29c8726d621
Create Date: 2023-11-21 22:21:54.929012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3615b26dece'
down_revision = 'd29c8726d621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    with op.batch_alter_table('client_animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('time_applied', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_animal', schema=None) as batch_op:
        batch_op.drop_column('time_applied')
        batch_op.drop_column('appointment_date')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
