"""empty message

Revision ID: d29c8726d621
Revises: 
Create Date: 2023-11-09 11:30:03.006505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29c8726d621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('unique_email_constraint', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_email_constraint'),
    sa.UniqueConstraint('username')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('unique_email_constraint', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('reason_to_qualify', sa.Text(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('number_of_pets', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name='fk_client_animal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_email_constraint')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('time_applied', sa.String(length=8), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tag_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('estimated_age', sa.Integer(), nullable=True),
    sa.Column('animal_status', sa.String(length=20), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_of_arrival', sa.Date(), nullable=True),
    sa.Column('animal_type', sa.String(length=50), nullable=True),
    sa.Column('coat_type', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('health_type', sa.String(length=50), nullable=True),
    sa.Column('dose', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('rabies_vaccination', sa.String(length=20), nullable=True),
    sa.Column('deworming', sa.String(length=20), nullable=True),
    sa.Column('health_frequency', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('date_adopted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_animal',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'animal_id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('time_applied', sa.String(length=8), nullable=True),
    sa.Column('application_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_volunteer_client_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    op.drop_table('client_animal')
    op.drop_table('animal_story')
    op.drop_table('animal_owner')
    op.drop_table('animal_health')
    op.drop_table('animal_details')
    op.drop_table('schedule')
    op.drop_table('client')
    op.drop_table('animal')
    op.drop_table('admin')
    # ### end Alembic commands ###
